config/routes.rb
FrozencdnFe::Application.routes.draw do

  match '/varnish_servers/distribute', :controller => 'varnish_servers', :action => 'distribute'

  match '/cache/:token/:action', :controller => 'varnish_caches', :via => :post

  resources :varnish_servers

  resources :websites
  resources :vcl

  devise_for :users

  root :to => "home#index"

end

app/models/website.rb
class Website < ActiveRecord::Base
  require Rails.root + "lib/applog"
  validates_uniqueness_of :token
  validates_presence_of :ttl
  validates :weburl,
    :presence => true,
    :uniqueness => true,
    :format => { :with => /^([a-zA-Z0-9_-]+(?:.[a-zA-Z0-9_-]+)*.[a-zA-Z]{2,4}(?:\/[a-zA-Z0-9_]+)*(?:\/[a-zA-Z0-9_]+.[a-zA-Z]{2,4}(?:\?[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)?)?(?:\&[a-zA-Z0-9_]+\=[a-zA-Z0-9_]+)*)$/i }  

  scope :active, where(:active => '1')
  scope :paid, where(:paid => '1')

  before_save :create_token

  # These need to be distributed every time they're created/updated/deleted.
  after_save :distribute_vcl, :log_updated 
  after_destroy :distribute_vcl, :log_deletion
  after_create :log_addition

  def create_token
    characters = ('a'..'z').to_a
    prefix = (0..1).map{characters.sample}.join
    new_time = Time.now
    new_token = new_time.to_i + rand(new_time.to_i)
    self.token = prefix + new_token.to_s(36) if self.token.blank?
  end

  def distribute_vcl
    varnish = VarnishServer.new
    varnish.distribute
  end

  def log_addition
    CUSTOM_LOGGER.info "Website Added: #{self.weburl}"
  end

  def log_deletion
    CUSTOM_LOGGER.info "Website Removed: #{self.weburl}"
  end

  def log_updated
    CUSTOM_LOGGER.info "Website Updated: #{self.weburl}"
  end

end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.page(params[:page]).accessible_by(current_ability)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @websites }
    end
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
    @website = Website.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @website }
    end
  end

  # GET /websites/new
  # GET /websites/new.json
  def new
    @website = Website.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @website }
    end
  end

  # GET /websites/1/edit
  def edit
    @website = Website.find(params[:id])
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(params[:website])
    @website.user_id = current_user.id
    
    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render json: @website, status: :created, location: @website }
      else
        format.html { render action: "new" }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /websites/1
  # PUT /websites/1.json
  def update
    @website = Website.find(params[:id])

    respond_to do |format|
      if @website.update_attributes(params[:website])
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website = Website.find(params[:id])
    @website.destroy

    respond_to do |format|
      format.html { redirect_to websites_url }
      format.json { head :ok }
    end
  end
end

app/helpers/websites_helper.rb
module WebsitesHelper
	def cdn_link(token)
		url = 'http://' + token + '.' + CDN_URL
		link_to(url, url)
	end
end

app/views/websites/_form.html.haml
.group
  = f.label :weburl, t("activerecord.attributes.website.weburl", :default => "Origin Server"), :class => :label
  = f.text_field :weburl, :class => 'text_field'
  %span.description Do NOT include http://
.group
  = f.label :vhost, t("activerecord.attributes.website.vhost", :default => "Virtual Host"), :class => :label
  = f.text_field :vhost, :class => 'text_field'
  %span.description Do NOT include http://
.group
  = f.label :ttl, t("activerecord.attributes.website.ttl", :default => "Ttl"), :class => :label
  = f.number_field :ttl, :class => 'number_field', :value => '600'
  %span.description Ex: a simple text
.group
  = f.label :active, t("activerecord.attributes.website.active", :default => "Active"), :class => :label
  = f.check_box :active, :class => 'check_box'
  %span.description Ex: a simple text
.group
  = f.label :paid, t("activerecord.attributes.website.paid", :default => "Paid"), :class => :label
  = f.check_box :paid, :class => 'check_box'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), websites_path, :class => "text_button_padding link_button"

app/views/websites/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/websites/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", websites_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_website_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_website_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Website
    .inner
      = form_for @website, :url => website_path(@website), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/websites/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", websites_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_website_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Websites
    .inner
      %table.table
        %tr
          %th
            = t("activerecord.attributes.website.weburl", :default => t("activerecord.labels.weburl", :default => "Url"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th= "CDN Prefix Link"
          %th.last &nbsp;
        - @websites.each do |website|
          %tr{:class => cycle("odd", "even")}
            %td
              = link_to website.weburl, website_path(website)
            %td
              = time_ago_in_words(website.created_at)
            %td
              = cdn_link(website.token)
              |
              = link_to("Clear Cache", "/cache/#{website.token}/clear?api_key=#{current_user.api_key}", :confirm => "Are you sure?", :remote => true, :method => 'post')
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", website_path(website)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_website_path(website)}
              |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", website_path(website), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
        = paginate @websites
- content_for :sidebar, render(:partial => 'sidebar')

app/views/websites/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", websites_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_website_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      Website
    .inner
      = form_for :website, :url => websites_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/websites/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", websites_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_website_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", website_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.website.weburl", :default => t("activerecord.labels.weburl", :default => "Origin Server"))
          \:
        = @website.weburl
      %p
        %b
          = t("activerecord.attributes.website.vhost", :default => t("activerecord.labels.vhost", :default => "Virtual Host"))
          \:
        = @website.vhost
      %p
        %b
          = t("activerecord.attributes.website.ttl", :default => t("activerecord.labels.ttl", :default => "Ttl"))
          \:
        = @website.ttl
      %p
        %b
          = t("activerecord.attributes.website.active", :default => t("activerecord.labels.active", :default => "Active"))
          \:
        = @website.active
      %p
        %b
          = t("activerecord.attributes.website.paid", :default => t("activerecord.labels.paid", :default => "Paid"))
          \:
        = @website.paid
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_website_path(@website), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), website_path(@website), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')