config/routes.rb
FrozencdnFe::Application.routes.draw do

  match '/varnish_servers/distribute', :controller => 'varnish_servers', :action => 'distribute'

  match '/cache/:token/:action', :controller => 'varnish_caches', :via => :post

  resources :varnish_servers

  resources :websites
  resources :vcl

  devise_for :users

  root :to => "home#index"

end

app/models/varnish_server.rb
class VarnishServer < ActiveRecord::Base
  require Rails.root + "lib/applog"

	def distribute
		VarnishServer.all.each do |server|
      		Resque.enqueue(VclDistributor, server.id)
    	end
	end

	def clear(url)
		VarnishServer.all.each do |server|
			Resque.enqueue(CacheClear, url, server.id)
      CUSTOM_LOGGER.info "Clearing #{url} on #{server.title} at #{server.ip}"
		end
	end
	
end

app/controllers/varnish_servers_controller.rb
class VarnishServersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /varnish_servers
  # GET /varnish_servers.json
  def index
    @varnish_servers = VarnishServer.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @varnish_servers }
    end
  end

  # GET /varnish_servers/1
  # GET /varnish_servers/1.json
  def show
    @varnish_server = VarnishServer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @varnish_server }
    end
  end

  # GET /varnish_servers/new
  # GET /varnish_servers/new.json
  def new
    @varnish_server = VarnishServer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @varnish_server }
    end
  end

  # GET /varnish_servers/1/edit
  def edit
    @varnish_server = VarnishServer.find(params[:id])
  end

  # POST /varnish_servers
  # POST /varnish_servers.json
  def create
    @varnish_server = VarnishServer.new(params[:varnish_server])

    respond_to do |format|
      if @varnish_server.save
        format.html { redirect_to @varnish_server, notice: 'Varnish server was successfully created.' }
        format.json { render json: @varnish_server, status: :created, location: @varnish_server }
      else
        format.html { render action: "new" }
        format.json { render json: @varnish_server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /varnish_servers/1
  # PUT /varnish_servers/1.json
  def update
    @varnish_server = VarnishServer.find(params[:id])

    respond_to do |format|
      if @varnish_server.update_attributes(params[:varnish_server])
        format.html { redirect_to @varnish_server, notice: 'Varnish server was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @varnish_server.errors, status: :unprocessable_entity }
      end
    end
  end

  def distribute
    varnish = VarnishServer.new
    varnish.distribute
    respond_to do |format|
      format.html { redirect_to varnish_servers_url, notice: 'Varnish configs were successfully pushed.' }
    end
  end

  # DELETE /varnish_servers/1
  # DELETE /varnish_servers/1.json
  def destroy
    @varnish_server = VarnishServer.find(params[:id])
    @varnish_server.destroy

    respond_to do |format|
      format.html { redirect_to varnish_servers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/varnish_servers_helper.rb
module VarnishServersHelper
end

app/views/varnish_servers/_form.html.haml
.group
  = f.label :title, t("activerecord.attributes.varnish_server.title", :default => "Title"), :class => :label
  = f.text_field :title, :class => 'text_field'
  %span.description What do we call this server.
.group
  = f.label :region, t("activerecord.attributes.varnish_server.region", :default => "Region"), :class => :label
  = f.text_field :region, :class => 'text_field'
  %span.description Region
.group
  = f.label :ip, t("activerecord.attributes.varnish_server.ip", :default => "Ip"), :class => :label
  = f.text_field :ip, :class => 'text_field'
  %span.description IP Address
.group
  = f.label :port, t("activerecord.attributes.varnish_server.port", :default => "Port"), :class => :label
  = f.text_field :port, :class => 'text_field'
  %span.description Port to Distribute VCL - usually 22
.group
  = f.label :vcluster_id, t("activerecord.attributes.varnish_server.vcluster_id", :default => "Cluster"), :class => :label
  = f.text_field :vcluster_id, :class => 'text_field'
  %span.description Cluster
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), varnish_servers_path, :class => "text_button_padding link_button"

app/views/varnish_servers/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "/varnish_servers/distribute"} Push out configs.

app/views/varnish_servers/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", varnish_servers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_varnish_server_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_varnish_server_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      VarnishServer
    .inner
      = form_for @varnish_server, :url => varnish_server_path(@varnish_server), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/varnish_servers/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", varnish_servers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_varnish_server_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      VarnishServers
    .inner
      %table.table
        %tr
          %th.first
            = t("activerecord.attributes.varnish_server.title", :default => t("activerecord.labels.title", :default => "Title"))
          %th= t("web-app-theme.region", :default => "Region") 
          %th= t("web-app-theme.ip", :default => "IP") 
          %th= t("web-app-theme.port", :default => "Port")  
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @varnish_servers.each do |varnish_server|
          %tr{:class => cycle("odd", "even")}
            %td
              = link_to varnish_server.title, varnish_server_path(varnish_server)
            %td
              = varnish_server.region
            %td
              = varnish_server.ip
            %td
              = varnish_server.port
            %td
              = varnish_server.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", varnish_server_path(varnish_server)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_varnish_server_path(varnish_server)} |
              |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", varnish_server_path(varnish_server), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
        = paginate @varnish_servers
- content_for :sidebar, render(:partial => 'sidebar')

app/views/varnish_servers/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", varnish_servers_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_varnish_server_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      VarnishServer
    .inner
      = form_for :varnish_server, :url => varnish_servers_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/varnish_servers/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", varnish_servers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_varnish_server_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", varnish_server_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.varnish_server.title", :default => t("activerecord.labels.title", :default => "Title"))
          \:
        = @varnish_server.title
      %p
        %b
          = t("activerecord.attributes.varnish_server.region", :default => t("activerecord.labels.region", :default => "Region"))
          \:
        = @varnish_server.region
      %p
        %b
          = t("activerecord.attributes.varnish_server.ip", :default => t("activerecord.labels.ip", :default => "Ip"))
          \:
        = @varnish_server.ip
      %p
        %b
          = t("activerecord.attributes.varnish_server.port", :default => t("activerecord.labels.port", :default => "Port"))
          \:
        = @varnish_server.port
      %p
        %b
          = t("activerecord.attributes.varnish_server.vcluster_id", :default => t("activerecord.labels.vcluster_id", :default => "Cluster"))
          \:
        = @varnish_server.vcluster_id
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_varnish_server_path(@varnish_server), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), varnish_server_path(@varnish_server), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')